spring:
  application:
    name: otoplug-rx-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.56.103:9092
      bindings:
        rx-topic:
          destination: tcs-log.v1
          group: otoplug-rx-service
          concurrency: 1
        output-topic:
          destination: output.v1
  kafka:
    bootstrap-servers: http://192.168.56.103:9092


logging:
  pattern:
    console: "[%d{yyyy-mm-dd HH:mm:ss.SSS}] %magenta([%thread]) %highlight([%level]) [%logger{36}.%M:%L]- %msg%n"
    file: "[%d{yyyy-mm-dd HH:mm:ss.SSS}] [%thread] [%level] [%logger{36}.%M:%L]- %msg%n"
  level:
    org.springframework.web: ERROR
    com.digiparts: DEBUG
  file:
    path: /service/otoplug/log/otoplug-rx-service/otoplug-rx-service.log
    max-history: 31
    max-size: 500MB


